/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package url.Formularios;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import url.modulo.controladoresBD.Clientes;
import url.controladores.ClientesJpaController;
import url.conexionBD.Conexion;
import url.modulo.clientes.AdaptarConsultaClientes;
import url.modulo.clientes.ConstruirConsultaClientes;
import url.modulo.clientes.ControladorEstrellas;
import url.modulo.clientes.RealizarConsultaCliente;
import url.modulo.inventario.Consultas;
import url.modulo.inventario.CrearConsulta;
import url.modulo.inventario.FiltroBusqueda;
import url.modulo.inventario.ObtenerConsulta;
import url.modulo.inventario.RealizarConsulta;

/**
 *
 * @author IsmarMiranda
 */
public class DialogClientes extends javax.swing.JDialog {
    
    EntityManager em =Conexion.obtenerConexion();
    ControladorEstrellas controlador;

    /**
     * Creates new form DialogClientes
     */
    public DialogClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        lbl1.setVisible(false);
        lbl2.setVisible(false);
        lbl3.setVisible(false);
        lbl4.setVisible(false);
        lbl5.setVisible(false);
 
       

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtCodig = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableClientes = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        txtSeleccion = new javax.swing.JTextField();
        comboTipoBusqueda = new javax.swing.JComboBox<>();
        txtCorreo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtFechaNacimiento = new javax.swing.JTextField();
        txtBuscar = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        txtEstrellas = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);
        jPanel1.add(txtCodig);
        txtCodig.setBounds(190, 50, 270, 30);

        tableClientes.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        tableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE", "TELEFONO", "FECHA NAC."
            }
        ));
        tableClientes.setRowHeight(35);
        jScrollPane1.setViewportView(tableClientes);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(60, 400, 930, 290);

        jButton2.setText("ingresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(730, 40, 110, 40);
        jPanel1.add(txtSeleccion);
        txtSeleccion.setBounds(550, 40, 160, 40);

        comboTipoBusqueda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboTipoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nombre" }));
        jPanel1.add(comboTipoBusqueda);
        comboTipoBusqueda.setBounds(560, 340, 160, 28);

        txtCorreo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtCorreo);
        txtCorreo.setBounds(190, 210, 270, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(740, 340, 110, 40);

        jLabel1.setText("Código:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 50, 70, 30);
        jPanel1.add(txtNombre);
        txtNombre.setBounds(190, 90, 270, 30);
        jPanel1.add(txtFechaNacimiento);
        txtFechaNacimiento.setBounds(190, 170, 270, 30);

        txtBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });
        jPanel1.add(txtBuscar);
        txtBuscar.setBounds(60, 340, 420, 40);
        jPanel1.add(txtTelefono);
        txtTelefono.setBounds(190, 130, 270, 30);

        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 90, 80, 30);

        jLabel3.setText("Teléfono:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 130, 90, 30);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("INGRESAR NUEVO CLIENTE");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(150, 10, 370, 30);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(500, 340, 40, 40);

        btnIngresar.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(0, 0, 255));
        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar);
        btnIngresar.setBounds(190, 260, 120, 50);

        jLabel6.setText("Correo");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 210, 120, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estrellaVacia.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(480, 170, 510, 70);

        lbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estrella.jpg"))); // NOI18N
        lbl5.setText("5");
        jPanel1.add(lbl5);
        lbl5.setBounds(890, 160, 100, 100);

        lbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estrella.jpg"))); // NOI18N
        lbl1.setText("1");
        jPanel1.add(lbl1);
        lbl1.setBounds(490, 150, 100, 100);

        lbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estrella.jpg"))); // NOI18N
        lbl2.setText("2");
        jPanel1.add(lbl2);
        lbl2.setBounds(590, 150, 100, 100);

        lbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estrella.jpg"))); // NOI18N
        lbl3.setText("3");
        jPanel1.add(lbl3);
        lbl3.setBounds(690, 150, 100, 100);

        lbl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estrella.jpg"))); // NOI18N
        lbl4.setText("4");
        jPanel1.add(lbl4);
        lbl4.setBounds(790, 150, 100, 100);

        btnActualizar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar);
        btnActualizar.setBounds(340, 260, 120, 50);

        txtEstrellas.setText("jLabel4");
        jPanel1.add(txtEstrellas);
        txtEstrellas.setBounds(0, -40, 1050, 730);

        jLabel9.setText("Fecha Nacimiento:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(60, 170, 120, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1054, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
       
       
        

    }//GEN-LAST:event_txtBuscarKeyTyped

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        //INGRESAMOS A LA TABLA EL CLIENTE NUEVO
        
        Clientes cliente = new Clientes();
        ClientesJpaController actualizarCliente = new ClientesJpaController(em);
        cliente.setCodigo(txtCodig.getText());
        cliente.setNombre(txtNombre.getText());
        cliente.setTelefono(txtTelefono.getText());
        cliente.setCumpleanios(txtFechaNacimiento.getText());
        cliente.setCorreo(txtCorreo.getText());
        cliente.setEstrellas(Integer.valueOf(txtEstrellas.getText()));
        actualizarCliente.create(cliente);
      
       
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        
        try {
        
        Clientes cliente = new Clientes();
        ClientesJpaController actualizarCliente = new ClientesJpaController(em);
        cliente.setCodigo(txtCodig.getText());
        cliente.setNombre(txtNombre.getText());
        cliente.setTelefono(txtTelefono.getText());
        cliente.setCumpleanios(txtFechaNacimiento.getText());
        cliente.setEstrellas(0);
        actualizarCliente.edit(cliente);
        
        } catch (Exception ex) {
            Logger.getLogger(DialogClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         FiltroBusqueda filtro = new FiltroBusqueda(txtBuscar.getText());
         CrearConsulta consulta = new ConstruirConsultaClientes(comboTipoBusqueda.getSelectedItem().toString());
         ObtenerConsulta obtenerConsulta= new ObtenerConsulta(consulta);
         obtenerConsulta.crearConsulta();
         Consultas consultaCliente = obtenerConsulta.obtenerConsulta();
         RealizarConsultaCliente consultar = new RealizarConsultaCliente(filtro);
         consultar.consultar(consultaCliente,em);
         AdaptarConsultaClientes adaptar = new AdaptarConsultaClientes(consultar.obtenerClienteses());
         tableClientes.setModel(adaptar.obtenerModelo());
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        //lbl1.setVisible(true);
// TODO add your handling code here:
        controlador = new ControladorEstrellas(Integer.parseInt((txtSeleccion.getText())),lbl1,lbl2,lbl3 ,lbl4,lbl5);
        controlador.controlarEstrellas();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogClientes dialog = new DialogClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboTipoBusqueda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JTable tableClientes;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCodig;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JLabel txtEstrellas;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSeleccion;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
